spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/kerp
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zc.sbm.entity